name: wayfinder_bloom
description: "Experience \\\"VoyageGuard,\\\" a smart travel companion that provides tourists with a secure digital ID, instant SOS assistance, and real-time geofencing alerts, while offering vital incident monitoring for police and insightful cluster heatmaps for tourism administrators."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  flutter_secure_storage: ^9.2.2
  flutter_local_notifications: ^17.2.3
  geofence_service: ^6.0.0+1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  flutter_map: ^8.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
